/**
 * The MaterialDesign Icons use in the extension
 * A subset of: {@link https://fonts.google.com/icons}
 */
export const MdiIcons = {
    clockLoader10: 'mdi-clock-loader-10',
    clockLoader20: 'mdi-clock-loader-20',
    clockLoader40: 'mdi-clock-loader-40',
    clockLoader60: 'mdi-clock-loader-60',
    clockLoader80: 'mdi-clock-loader-80',
    clockLoader90: 'mdi-clock-loader-90',
    description: 'mdi-description',
    descriptionFill: 'mdi-description-fill',
    draft: 'mdi-draft',
    folder: 'mdi-folder',
    folderOpen: 'folder_open',
    formatLineSpacing: 'mdi-format-line-spacing',
    hourglassDisabled: 'mdi-hourglass-disabled',
    hourglassEmpty: 'mdi-hourglass-empty',
    link: 'mdi-link',
    linkOff: 'mdi-link_off',
    splitscreenBottom: 'mdi-splitscreen-bottom',
    splitscreenTop: 'mdi-splitscreen-top',
    swapVert: 'mdi-swap-vert',
    taskAlt: 'mdi-task-alt',
    verticalAlignBottom: 'mdi-vertical-align-bottom',
    verticalAlignTop: 'mdi-vertical-align-top',
    verticalDistribute: 'mdi-vertical-distribute',
};

export const CodeIcons = [
    "add",
    "azure",
    "arrow-both",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-small-down",
    "arrow-small-left",
    "arrow-small-right",
    "arrow-small-up",
    "arrow-up",
    "beaker",
    "bell",
    "bold",
    "book",
    "bookmark",
    "briefcase",
    "broadcast",
    "browser",
    "bug",
    "calendar",
    "case-sensitive",
    "check",
    "checklist",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "chrome-close",
    "chrome-maximize",
    "chrome-minimize",
    "chrome-restore",
    "circle-filled",
    "circle-outline",
    "clock",
    "clone",
    "close",
    "cloud",
    "cloud-download",
    "cloud-upload",
    "code",
    "collapse-all",
    "color-mode",
    "comment",
    "comment-add",
    "comment-discussion",
    "credit-card",
    "dash",
    "dashboard",
    "database",
    "debug",
    "device-camera",
    "device-camera-video",
    "device-desktop",
    "device-mobile",
    "diff",
    "discard",
    "edit",
    "editor-layout",
    "ellipsis",
    "empty-window",
    "error",
    "exclude",
    "expand-all",
    "extensions",
    "eye",
    "eye-closed",
    "file",
    "file-binary",
    "file-code",
    "file-media",
    "file-pdf",
    "file-submodule",
    "file-symlink-directory",
    "file-symlink-file",
    "file-zip",
    "files",
    "filter",
    "flame",
    "fold",
    "folder",
    "folder-active",
    "folder-opened",
    "gear",
    "gift",
    "gist-secret",
    "git-commit",
    "git-compare",
    "git-merge",
    "git-pull-request",
    "github-action",
    "heart",
    "history",
    "home",
    "horizontal-rule",
    "hubot",
    "inbox",
    "info",
    "issue-closed",
    "issue-opened",
    "issue-reopened",
    "italic",
    "jersey",
    "json",
    "kebab-vertical",
    "key",
    "law",
    "lightbulb",
    "link",
    "link-external",
    "list-ordered",
    "list-unordered",
    "live-share",
    "loading",
    "location",
    "lock",
    "log-out",
    "mail",
    "mail-read",
    "mail-reply",
    "mark-github",
    "markdown",
    "megaphone",
    "mention",
    "milestone",
    "mortar-board",
    "move",
    "multiple-windows",
    "mute",
    "no-newline",
    "note",
    "octoface",
    "open-preview",
    "organization",
    "output",
    "package",
    "paintcan",
    "pencil",
    "person",
    "pin",
    "play",
    "plug",
    "preserve-case",
    "preview",
    "project",
    "pulse",
    "question",
    "quote",
    "radio-tower",
    "reactions",
    "record",
    "references",
    "refresh",
    "regex",
    "remote-explorer",
    "remote",
    "remove",
    "replace",
    "replace-all",
    "reply",
    "repo",
    "repo-clone",
    "repo-force-push",
    "repo-pull",
    "repo-push",
    "report",
    "request-changes",
    "rocket",
    "rss",
    "ruby",
    "save",
    "screen-full",
    "screen-normal",
    "search",
    "server",
    "settings-gear",
    "settings",
    "shield",
    "sign-in",
    "sign-out",
    "smiley",
    "sort-precedence",
    "split-horizontal",
    "split-vertical",
    "square",
    "squirrel",
    "star",
    "stop",
    "sync",
    "tag",
    "tasklist",
    "telescope",
    "terminal",
    "text-size",
    "three-bars",
    "thumbsdown",
    "thumbsup",
    "tools",
    "trash",
    "triangle-down",
    "triangle-left",
    "triangle-right",
    "triangle-up",
    "unfold",
    "unlock",
    "unmute",
    "unverified",
    "verified",
    "versions",
    "vm-active",
    "vm-outline",
    "vm-running",
    "watch",
    "whitespace",
    "whole-word",
    "window",
    "word-wrap",
    "zoom-in",
    "zoom-out"
];


export const allKnownIcons: string[] = [
    ...Object.values(MdiIcons).map(v => v.toString()),
    ...CodeIcons
];
